#!/bin/env bash

Xephyr -ac -screen 2560x1080 -br -reset -terminate :420 &
export DISPLAY=:420
sleep 1

make clean
make

if [[ ":$PATH:" != *":$XDG_CONFIG_HOME/scripts/:"* ]]; then
    export PATH="$PATH:$XDG_CONFIG_HOME/scripts/"
fi

eww open statusbar

while type dwm >/dev/null; do
    ./dwm && continue || break
done
