#!/bin/env bash

Xephyr -ac -screen 2560x1080 -br -reset -terminate :420 &
export DISPLAY=:420
sleep 1

make clean
make

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ ":$PATH:" != *":$BASE_DIR/scripts/:"* ]]; then
    export PATH="$PATH:$BASE_DIR/scripts/"
fi

while type dwm >/dev/null; do
    ./dwm && continue || break
done
